'use client';
import './globals.css'
import NavBar from '../components/navBar'


import { auth } from "../firebaseConfig";
import { useAuthState } from "react-firebase-hooks/auth";

import ChatBox from "../components/chat/chatBox"
import Welcome from '../components/chat/Welcome';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  const [user] =useAuthState(auth);
  return (
    <html lang="en">
       <head />
      <body><NavBar/>
      <div>
      {!user? <Welcome /> :<ChatBox /> } 
      </div>
      {children}
      </body>
    </html>
  )
}
